### ISSUE TITLE
[disc5] Windows failure with ERROR_INVALID_NETNAME.

### ISSUE THREAD

**Issue by cheatfate** [status-im/nim-eth#177]
I'm receiving a lot of such things.

```
{"lvl":"DBG","ts":"2020-02-25 21:40:57+02:00","msg":"Discovery send failed","topics":"discv5","tid":14136,"msg":"(1214) The format of the specified network name is invalid.\r\n","node":"3"}
```

Error 1214 means [ERROR_INVALID_NETNAME](https://docs.microsoft.com/en-us/windows/desktop/debug/system-error-codes--1000-1299-).

I think this happens because we are sending our messages to `0.0.0.0` (https://superuser.com/questions/1030329/better-to-block-a-host-to-0-0-0-0-than-to-127-0-0-1)

**Comment by cheatfate** [comment]
I have made some changes and now i see destination addresses discoveryv5 is trying to send.
```
{"lvl":"DBG","ts":"2020-02-25 22:14:15+02:00","msg":"Discovery send failed","topics":"discv5","tid":11244,"msg":"(1214) The format of the specified network name is invalid.\r\n","remote":"0.0.0.0:30001","node":"3"}
{"lvl":"DBG","ts":"2020-02-25 22:14:15+02:00","msg":"Discovery send failed","topics":"discv5","tid":11244,"msg":"(1214) The format of the specified network name is invalid.\r\n","remote":"0.0.0.0:30000","node":"3"}
{"lvl":"DBG","ts":"2020-02-25 22:14:15+02:00","msg":"Discovery send failed","topics":"discv5","tid":11244,"msg":"(1214) The format of the specified network name is invalid.\r\n","remote":"0.0.0.0:30002","node":"3"}
{"lvl":"DBG","ts":"2020-02-25 22:14:16+02:00","msg":"Discovery send failed","topics":"discv5","tid":11244,"msg":"(1214) The format of the specified network name is invalid.\r\n","remote":"0.0.0.0:30002","node":"3"}
{"lvl":"DBG","ts":"2020-02-25 22:14:16+02:00","msg":"Discovery send failed","topics":"discv5","tid":11244,"msg":"(1214) The format of the specified network name is invalid.\r\n","remote":"0.0.0.0:30001","node":"3"}
{"lvl":"DBG","ts":"2020-02-25 22:14:16+02:00","msg":"Discovery send failed","topics":"discv5","tid":11244,"msg":"(1214) The format of the specified network name is invalid.\r\n","remote":"0.0.0.0:30000","node":"3"}
{"lvl":"DBG","ts":"2020-02-25 22:14:16+02:00","msg":"Discovery send failed","topics":"discv5","tid":11244,"msg":"(1214) The format of the specified network name is invalid.\r\n","remote":"0.0.0.0:30001","node":"3"}
{"lvl":"DBG","ts":"2020-02-25 22:14:16+02:00","msg":"Discovery send failed","topics":"discv5","tid":11244,"msg":"(1214) The format of the specified network name is invalid.\r\n","remote":"0.0.0.0:30000","node":"3"}
{"lvl":"DBG","ts":"2020-02-25 22:14:16+02:00","msg":"Discovery send failed","topics":"discv5","tid":11244,"msg":"(1214) The format of the specified network name is invalid.\r\n","remote":"0.0.0.0:30002","node":"3"}
```

Such sending on *nix platforms are legal and it actually will be send to `127.0.0.1`, but its not legal on Windows.

**Comment by cheatfate** [comment]
I have changed Windows behavior to be compatible with BSD behavior in https://github.com/status-im/nim-chronos/pull/79
But i still think there something wrong, if we need to send messages to `0.0.0.0`.
Feel free to close this issue, if you do not think its a problem.

**Comment by kdeme** [comment]
I do consider it an issue to pass the `any` address to discovery, but not necessarily an issue of the discovery code.
I mean, sure, we could provide some check for `any` address in discovery, and if true, alter it to e.g. the loopback address or just quit or similar. However, I believe this shouldn't really go in the discovery code, the check should be done a step earlier before passing this to discovery start-up imo.

However, we could change the API to help with this. E.g. the `newProtocol` call could make the `IpAddress` parameter an `Option`. If not set, it could default e.g. to the loopback address.
With discovery v5 there is also the option to omit the ip address in the ENR (and discover your own ip address via returned ip address in a pong packet). This could be done by just providing `none()`, or it could be defaulted instead of the loopback mentioned above.
 
And perhaps something that does belong in discovery is on the other end: ignore nodes with ENRs that advertise an `any` address in their ENR/Enode.

**Comment by kdeme** [comment]
This is addressed by https://github.com/status-im/nim-eth/pull/202
- IP address in ENRs are checked when received from Nodes packet
- IP address from ENR at handshake is checked with address from UDP endpoint
- Added IP address as an `Option` in `newProtocol` so that it is more clear when to create an ENR without IP address.
