### ISSUE TITLE
Unintuitive error in `p2pProtocol` macro

### ISSUE THREAD

**Issue by nolash** [status-im/nim-eth#91]
Embarking on my first nim-devp2p hello world adventure, I was stumped for awhile by the following situation:

```
import
  eth/p2p, chronos, chronicles, chronos/timer

const
  bzzVersion = 42

p2pProtocol Bzz(version = bzzVersion):

  proc hellooo(peer: Peer,
    foo: string) =
     echo foo
    
  onPeerConnected do (peer: Peer):
    warn "conn"
    if peer.supports(Bzz):
      warn "bzz"
      waitFor peer.hellooo("bar")
      waitFor sleepAsync(1000)
```

Compiling this returned the following error:

```
/home/lash/src/status/nim-eth/eth/rlp.nim(377, 18) Error: type mismatch: got <Rlp, type string>
but expected one of: 
proc read[T](future: Future[T] | FutureVar[T]): T
  first type mismatch at position: 1
  required type: Future[read.T] or FutureVar[read.T]
  but expression 'rlp' is of type: Rlp
proc read(rstream: AsyncStreamReader; n = 0): Future[seq[byte]]
  first type mismatch at position: 1
  required type: AsyncStreamReader
  but expression 'rlp' is of type: Rlp
proc read(transp: StreamTransport; n = -1): Future[seq[byte]]
  first type mismatch at position: 1
  required type: StreamTransport
  but expression 'rlp' is of type: Rlp

expression: read(rlp, type(result.foo))
```

Turns out the `p2pProtocol` is a macro, and it inserts code that refers to the `rlp` namespace. Adding `eth/rlp` to the imports in the code solved the error.

It was however not so easy to understand the error context, so maybe it could be improved.

**Comment by kdeme** [comment]
Thanks for reporting this. It would indeed be better if this import would not be needed.
Furthermore, I noticed that without `import chronicles` there is another compile error.

@zah how to resolve these best?

Side note: you should not use `waitFor` but `await` instead in `onPeerConnected`. It might not be clear as it is abstracted away because of the macro but this is actually an `async proc`. `waitFor` should only be used at "top level", if you use it in `async` procs then you introduce basically a `poll()` inside a `poll()` which can/will cause problems.
Ideally this wrong usage should generate a compile error, and in the future it probably will do so.

**Comment by stefantalpalaru** [comment]
How about exporting all those modules that are required by the macro from the macro's module?

**Comment by kdeme** [comment]
Yes, and that is OK for rlp.
However, for chronicles it is rather dirty and hence my question if it can be fixed better.

Anyway, https://github.com/status-im/nim-eth/pull/93
